name: Teardown DEV

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  destroy:
    name: Teardown DEV
    uses: ./.github/workflows/teardown-reusable.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_DEV }}
      aws_region: ${{ vars.AWS_REGION }}
      cdk_env: ${{ vars.CDK_ENV_DEV }}
    secrets: inherit
